### PR TITLE
General Fixes + now works in ruby 1.9

### PR DESCRIPTION
**Pull request by iajrz**
To make it run out of the box with a fresh install by just following the instructions.

### CODE REVIEW

**Comment by kyrylo** [comment]
We use Pookie D. Bot at our corporation (Sirius Bees Ness Ltd), but we still run Ruby 1.7.3. We've been evaluating the possibility of the upgrade to 1.9, but we're not sure of its maturity. That said, we'd like to see this patch merged, because it will be very useful when we upgrade our app.

P.S. We're hiring hipster rockstar Prolog devs. Our FidoNet address is 1:105/6.42.

**Comment by epitron** [comment]
Oh man! I never saw this!

Thanks for all the patches, @iajrz! I'll chuck these in.

**Comment by epitron** [comment]
@kyrylo We're working on compatability for Ruby 1.7 and 1.3. We're hoping to have it rolled out by 2052.

**Comment by epitron** [comment]
Fixed applied!

**Pull request closed without merging**
